version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    networks:
      - server-network

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    networks:
      - server-network
    command: npx nodemon server # overrides CMD from dockerfile

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - backend
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    networks:
      - server-network
    command: yarn start

 
#Docker Networks
networks:
  server-network:
    driver: bridge
    external: true
#Volumes
volumes:
  dbdata:
    driver: local

